### ISSUE TITLE
Blog post obsolete

### ISSUE THREAD

**Issue by MMDF** [jameshfisher/jameshfisher.com#16]
https://jameshfisher.com/2017/08/30/how-do-i-make-a-full-width-iframe/
This blog post's examples don't work as intended on the latest Chrome.

**Comment by jameshfisher** [comment]
Hey, thanks for flagging this! You're right.

Actually, I think I've fucked this up by changing my blog's layout.

I stated in the post that

> we can use the padding-top property with a percentage, which is proportional to its own width.

which is actually wrong. More precisely,

> we can use the padding-top property with a percentage, which is proportional to the width of the parent element.

If you wrap the examples in an additional `<div>...</div>`, it works again.

I'll correct the post.

**Comment by MMDF** [comment]
Actually i'd say this post here has a better solution: https://fettblog.eu/blog/2013/06/16/preserving-aspect-ratio-for-embedded-iframes/ It uses padding-bottom (doesn't make a difference to use top either) to set the height proportional and uses position:absolute to ignore padding but height:100% to take advantage of the padding.

Of course, it's your choice which you'd like to put in your post, just a suggestion

**Comment by jameshfisher** [comment]
Yup - looks pretty similar. I've fixed the post (and some iframes I had elsewhere on the site, which I had also broken ...)

**Comment by jameshfisher** [comment]
Thanks again for bringing it to my attention :-)
